CREATE OR REPLACE PROCEDURE RANKING
IS
BEGIN
  UPDATE T_SEJ_HISTORICO
  SET T_SEJ_HISTORICO.nr_posAula=
    (SELECT T1.rank FROM(
      SELECT CD_ALUNO,
       CD_AULA,
       NR_ACERTO,
       NR_ERRO,
       RANK() OVER (PARTITION BY CD_AULA ORDER BY NR_ACERTO - NR_ERRO DESC) AS rank
      FROM T_SEJ_HISTORICO
    ) T1
    WHERE T1.CD_ALUNO = T_SEJ_HISTORICO.cd_aluno 
    AND T1.CD_AULA = T_SEJ_HISTORICO.cd_aula
  );
  
UPDATE T_SEJ_HISTORICO
  SET T_SEJ_HISTORICO.NR_POSTOTAL=
    (SELECT rank2 FROM(
      SELECT CD_ALUNO,
       NR_ACERTO,
       NR_ERRO,
       DENSE_RANK() OVER (ORDER BY NR_ACERTO - NR_ERRO DESC) AS rank2
      FROM T_SEJ_HISTORICO
    ) T1
    WHERE T1.CD_ALUNO = T_SEJ_HISTORICO.CD_ALUNO
  );
  
END RANKING;